### ISSUE TITLE
Remove dependency on puppet_classify

### ISSUE THREAD

**Issue by jolshevski** [puppetlabs/prosvcs-node_manager#14]
For ease of use, we should remove the dependency on the puppet_classify gem. This will reduce the amount of effort required to use the module by removing a manual installation step. 

Accomplishing this will require reimplementing communications with the node classifier service. See the PuppetDB terminus for reference, and leverage Puppet internal network communications scaffolding instead of raw Net::HTTP.

**Comment by WhatsARanjit** [comment]
Originally, it didn't require the gem, but I was told this is how we wanted standardize things.  In PR #10 , we added a feature to ensure the gem is available first.

**Comment by jolshevski** [comment]
Yeah using a shared library is nice, but at the cost of an additional manual installation step for the user? I'm not against using puppet_classify, but I think the design decision is worth reconsidering if we want this module to gain community adoption.

**Comment by Sharpie** [comment]
> but at the cost of an additional manual installation step for the user? 

Now that #10 is merged, Puppet can install the gem and then manage `node_group` resources --- all in one run. For example, on PE 3.8:

```puppet
class profile::pe::node_groups {


  # FIXME: When 4.0 ships, the pe_puppetserver_gem provider can be used to do
  # this.
  exec {'install puppetclassify for pe-puppetserver':
    command => 'puppetserver gem install puppetclassify',
    path    => "/opt/puppet/bin:${::path}",
    # This is more efficient than running `puppetserver gem list`
    unless  => '/bin/ls /var/opt/lib/pe-puppet-server/jruby-gems/gems/puppetclassify*',
  }

  # FIXME: When 4.0 ships, the puppet_gem provider can be used to do this.
  package {'puppetclassify':
    ensure   => present,
    provider => pe_gem,
  }

  create_resources(node_group, hiera_hash('node_groups'), {
    ensure => present,
  })

}
```

The Transaction will defer `node_group` resources until the `puppetclassify` gem is installed --- but an explicit `require` could be thrown in to make things less magical.

**Comment by WhatsARanjit** [comment]
Closing issue because the puppetclassify feature eases this.
