### ISSUE TITLE
Ability to 'auto' create groups based on a regex search. ( Create 'Roles' as groups )

### ISSUE THREAD

**Issue by smbambling** [puppetlabs/prosvcs-node_manager#18]
I wasn't sure if you guys wanted to expand this module to include a feature to grant the ability to auto create groups in the PE console from a regex search for classes.

I plan to use this for auto creating a group for each Role class that is created.  This would require a custom fact called 'role' that is placed on each node to assist in the auto configuration.  

I have two gist a function and an example class that could be used to accomplish this.  If this is something that you would be interested in I would submit a formal PR with the changes.

Fetch Function: https://gist.github.com/smbambling/4bb393aa509236c419ec
Example Class: https://gist.github.com/smbambling/2f7c4bd92e3519fe4a00

**Comment by jolshevski** [comment]
Hey Steven, terrific idea. I went ahead and wrote up a function that implements this concept using Puppet internals instead of the API. Feel free to weigh in on the conversation on PR #19. Thanks!
