### ISSUE TITLE
Node groups don't allow : even though the classifier does

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/prosvcs-node_manager#3]
https://github.com/puppetlabs/prosvcs-node_manager/blob/master/lib/puppet/type/node_group.rb#L8

Looks like the regex is just too strong and doesn't allow for :

http://rubular.com/r/GTErAc61cN

I added in a colon and it looks like it will work.  

http://rubular.com/r/9yVSOUOzQ0

**Comment by jolshevski** [comment]
Addressed in PR #12
