### ISSUE TITLE
No provider for node_group

### ISSUE THREAD

**Issue by gjngeldenhuis** [puppetlabs/prosvcs-node_manager#41]
When running:
puppet apply test.pp on a PE2015.3.1 server with Ubuntu 14.04 you get:
Notice: Compiled catalog for puppet.skyscape.com in environment production in 0.04 seconds
Error: Could not find a suitable provider for node_group

test.pp
```
node_group { 'Test':
  ensure => present,
  environment => 'production',
}
```

You do get a response back if you do puppet describe node_group so the code is accessible.  Location did not seem to matter for the module. I tried both /opt/puppetlabs/puppet/modules/ or /etc/puppetlabs/code/environments/production/modules. In each case I restarted the pe-puppetserver just to be sure there is no code caching.

**Comment by gjngeldenhuis** [comment]
@WhatsARanjit the README suggests to contact individuals who wrote the code and you seem to be the primary author of the provider. Your assistance would be greatly appreciated.

**Comment by WhatsARanjit** [comment]
@gjngeldenhuis When you are running commands that require gems with puppet on the CLI, you need to have the gems installed via `/etc/puppetlabs/puppet/bin/gem`.  When the puppetserver needs the power of those gems, they actually have to be installed into the puppetserver's embedded Ruby stack.  Take a look at this:
https://docs.puppetlabs.com/puppetserver/latest/gems.html#installing-and-removing-gems

Hopefully that's helpful.  We do have a PR https://github.com/puppetlabs/prosvcs-node_manager/pull/39/files incoming which will let you add a class which installs the gem in the correct spot for you.

**Comment by gjngeldenhuis** [comment]
@WhatsARanjit I have installed the gem but am still getting the same error as before. 
which is:
```
Error: Could not find a suitable provider for node_group
```
when I run puppet apply against:
```
node_group { 'Test':
  ensure => present,
  environment => 'production',
}
```

If I run puppet apply against:
```
file { '/tmp/test':
  ensure  => file,
  content => node_groups(),
}
```
Then I get: 
```
Error: Evaluation Error: Error while evaluating a Function Call, uninitialized constant Puppet::Util::Node_groups::PuppetClassify at /root/test.pp:3:14 on node
```

**Comment by gjngeldenhuis** [comment]
Just to be clear I installed the gem doing: ```puppetserver gem install puppetclassify```

**Comment by WhatsARanjit** [comment]
So there are two Ruby environments happening here- agent and server.  When the puppetserver is in action here, it uses a separate set of gems than the puppet agent.  When running `puppet apply`, which doesn't require a master/server, it doesn't use the master's gems.  You'll want to install the puppetclassify gem in both locations so the server can use it, as well as the agent.

```
[root@master ~]# /opt/puppetlabs/puppet/bin/gem list puppetclassify

*** LOCAL GEMS ***

puppetclassify (0.1.3)
[root@master ~]# /opt/puppetlabs/bin/puppetserver gem list puppetclassify

*** LOCAL GEMS ***

puppetclassify (0.1.3)
```

**Comment by gjngeldenhuis** [comment]
@WhatsARanjit super!!! Working now. Thank you very much for the very clear explanation, it has been super helpful. Is there any way I can help to get Adam's PR moved along? I understood there was some discussion about the best implementation...
