### ISSUE TITLE
add description attribute

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/prosvcs-node_manager#44]
#When exporting node group info from the API a group comes with a optonal description field.  We should be able to populate this via a puppet type.

**Comment by WhatsARanjit** [comment]
Not sure why I didn't add this to begin with.  Maybe it wasn't in the API at some point?  I'd like to verify but adding it should be easy enough.

**Comment by WhatsARanjit** [comment]
Migrated to: https://github.com/WhatsARanjit/prosvcs-node_manager/issues/10

**Comment by WhatsARanjit** [comment]
@logicminds Merged changes for this.  Should go out next release.

https://github.com/WhatsARanjit/prosvcs-node_manager/commit/914eaf9374a0aa704e633dc61a0ef7290d1858f6
