### ISSUE TITLE
groups are not idempotent when multiple classes are used

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/prosvcs-node_manager#46]
Because the classes are expressed in a hash puppet will compare the hash as a whole instead of doing a deep inspection of the items that might have changed in the hash.  So each puppet run is no longer idempotent because the order of the hash is always different thus triggering a change.

We will need to inspect the change_to_hash and the current_hash for the classes and args so that the data is inspected and not just the order of contents.

`(hash1.to_a - hash2.to_a).empty?`  -- possible solution ?

The PE puppet master group is a good example case since it comes with many classes by default.

**Comment by WhatsARanjit** [comment]
Migrated to https://github.com/WhatsARanjit/prosvcs-node_manager/issues/9

**Comment by WhatsARanjit** [comment]
@logicminds Introduced some deep-sorting for the `classes` Hash on the type side as well as the provider side.  If you'd like to test, I appreciate any feedback.

https://github.com/WhatsARanjit/prosvcs-node_manager/tree/hash_order
