### ISSUE TITLE
empty class parameters list accepted but does not update target

### ISSUE THREAD

**Issue by GeoffWilliams** [puppetlabs/prosvcs-node_manager#48]
It seems not possible at the moment to remove a list of parameters from a class, eg:

```
node_group { 'PE Agent':
  ensure               => 'present',
  classes              => {'puppet_enterprise::profile::agent' => {}},
  environment          => 'production',
  override_environment => 'false',
  parent               => 'PE Infrastructure',
  rule                 => ['and', ['~', ['fact', 'aio_agent_version'], '.+']],
}
```

Does not remove the parameter `puppet_enterprise::profile::agent::manage_symlinks` if its already set.  It would be cool if this was possible

## Workaround
Set the parameters that need removing/resetting explicitly, eg:

```
    node_group { 'PE Agent':
      ensure               => 'present',
      classes              => {'puppet_enterprise::profile::agent' => {'manage_symlinks' => $manage_symlinks}},
      environment          => 'production',
      override_environment => 'false',
      parent               => 'PE Infrastructure',
      rule                 => ['and', ['~', ['fact', 'aio_agent_version'], '.+']],
    }
```

**Comment by natemccurdy** [comment]
Should it be able to? That behavior may not be desired, at least by default. Also, what does the API do when you pass it an empty hash of class parameters?

In your workaround, is `$manage_symlinks` set to `undef` or `false`?

**Comment by WhatsARanjit** [comment]
Migrated to: https://github.com/WhatsARanjit/prosvcs-node_manager/issues/11

**Comment by WhatsARanjit** [comment]
@GeoffWilliams FIxed in https://github.com/WhatsARanjit/prosvcs-node_manager/pull/14.
